name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g., v1.0, v2.0.1)

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${{ github.ref }} | sed 's/refs\\/tags\\///g')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            YOUR_DOCKER_HUB_USERNAME/azure-storage-mover:${{ steps.extract_tag.outputs.tag }}
            YOUR_DOCKER_HUB_USERNAME/azure-storage-mover:latest

